### PR TITLE
Replace confusing $ie-font-ratio variable with $browser-default-font-size in vertical_rhythm partial

### PR DESCRIPTION
**Pull request by JohnAlbin**
This commit is for the discussion in #766. Comments should go in that discussion thread, not this one.

### CODE REVIEW

**Comment by mirisuzanne** [comment]
+1

**Comment by chriseppstein** [comment]
Regarding the variable. I doubt anyone is using it so it's fine if it goes w/o a deprecation (and it's easy for them to fix it if it is in use). However, I'd like to understand what are the ramifications of moving the styles to the `html` element to existing users. This aspect seems like it deserves a changelog entry at least explaining that these styles moved and why. Thoughts?

**Comment by scottdavis** [comment]
i agree and  i just noticed that when i viewed the diff this needs some kind if description

**Comment by chriseppstein** [comment]
I decided to land this on stable. Seems harmless enough after thinking about it more carefully. Merged as: 48bfe186afb871139577303626e6decd8726c9b6

**Pull request closed without merging**
