### PR TITLE
Allow inline_image() to find image assets in bundled gem

### PR DESCRIPTION
**Pull request by beausmith**
Use image_path_for_size() to ask sprockets for outside asset paths if image asset is not found among application assets.

_I've locally tested this by moving an asset from the app to the gem and back. I'd like to add actual tests for this, but 1. there aren't any existing tests to update for this existing feature, 2. I'm really not sure how to test this code when an asset is being included into another project though a gem, 3. Still aspiring to earn "rubyist" cred._ =)

### CODE REVIEW

**Comment by beausmith** [comment]
Fixes issue #1644

**Comment by scottdavis** [comment]
may want to rebase this on master a lot has changed

**Comment by beausmith** [comment]
Sure @scottdavis, I'll rebase on master and update my branch. As I see on master the file moved to a new location, so it's an easy change.

**Comment by scottdavis** [comment]
Thanks!

**Comment by beausmith** [comment]
New pull request: https://github.com/chriseppstein/compass/pull/1649

**Pull request closed without merging**
