### PR TITLE
Fix encoding for Ruby 2.0.0 compatibility

### PR DESCRIPTION
**Pull request by voxik**

### CODE REVIEW

**Comment by scottdavis** [comment]
does this pass under 1.8.7 and 1.9.x?

**Comment by voxik** [comment]
I did not tested, but it should work for 1.9.x but not for 1.8.7, since there was nothing know about encoding yet.

**Comment by voxik** [comment]
Actually, the other option is to used # encoding: ascii-8bit directive at the beginning of the file. Not sure if that is better, but it should work everywhere, i.e. Ruby 1.8.7 will happily ignore the directive.

**Comment by scottdavis** [comment]
Im getting test failures under ruby 2.0.0p0 (2013-02-24 revision 39474) [x86_64-darwin11.4.2]

```
Failure:
test_to_blob(CompassPngTest)
/Users/sdavis/Work/compass/test/units/compass_png_test.rb:39:in `test_to_blob'
     36:   def test_to_blob
     37:     png = Compass::PNG.new(5,10, [255,255,255])
     38:     blob = 'iVBORw0KGgoAAAANSUhEUgAAAAUAAAAKCAIAAADzWwNnAAAAD0lEQVR4nGP4jwoYBhkfALRylWv4Dj0LAAAAAElFTkSuQmCC'.unpack('m*').first
  => 39:     assert_equal blob, png.to_blob
     40:
     41:     png = Compass::PNG.new(10,5, [32,64,128])
     42:     blob = 'iVBORw0KGgoAAAANSUhEUgAAAAoAAAAFCAIAAADzBuo/AAAAEUlEQVR4nGNQcGjAgxgGUBoALT4rwRTA0gkAAAAASUVORK5CYII='.unpack('m*').first
/Users/sdavis/.rvm/gems/ruby-2.0.0-p0/gems/mocha-0.11.4/lib/mocha/integration/test_unit/gem_version_230_to_240.rb:25:in `run'
<"\x89PNG\r\n\x1A\n\0\0\0\rIHDR\0\0\0\x05\0\0\0\n\b\x02\0\0\0\xF3[\x03g\0\0\0\x0FIDATx\x9Cc\xF8\x8F\n\x18\x06\x19\x1F\0\xB4r\x95k\xF8\x0E=\v\0\0\0\0IEND\xAEB`\x82"> expected but was
<"\x89PNG\r\n\x1A\n\0\0\0\rIHDR\0\0\0\x05\0\0\0\n\b\x02\0\0\0\xF3[\x03g\0\0\0\x11IDATx\x9Cc8\xBC\x1F\x1Fd\x18\x95\xC6\x06\x01\xFA\xFE\xE2-\xC8\x99\xE2/\0\0\0\0IEND\xAEB`\x82">

diff:
  �PNG

IHDR
?�[gIDATx�c�
?                    8�d�����-ș�/IEND�B`�
- �r�k�=
        IEND�B`�
===============================================================================
```

**Comment by voxik** [comment]
Yes, I observe this issue as well. Did not found what is the reason for this issue and I don't think it is just Ruby 2.0.0 issue, since I am afraid I observed the same issue on Fedora 18 with Ruby 1.9.3. My guess is either Zlib or some weird pack issue. Not sure.

**Pull request closed without merging**
