### PR TITLE
sprite_file

### PR DESCRIPTION
**Pull request by brewster1134**

### CODE REVIEW

**Comment by scottdavis** [comment]
Whats the status of this?

**Comment by brewster1134** [comment]
@scottdavis was that directed to me?

**Comment by scottdavis** [comment]
no just more of a note

**Comment by scottdavis** [comment]
This breaks all kinds of tests

**Comment by scottdavis** [comment]
closing since you have reverted

**Comment by brewster1134** [comment]
@scottdavis not sure what you mean by having reverted.  I will try to find some time to reproduce the issues and write some specs against it.

**Comment by brewster1134** [comment]
well... i just updated to the latest prerelease alpha.21, and i cannot reproduce. :)

**Comment by brewster1134** [comment]
false positive!  i was tired on not testing the correct thing.  i can reproduce it with the latest alpha on the following repo

``` shell
git clone https://github.com/brewster1134/test.git
git checkout compass_1665
```

`bundle exec rake release` succeeds
`bundle exec guard` fails

with the changes from this PR, both succeed.  as i started to silo the issue, i realize it could be konacha or guard related, but patching the compass sprite file fixes it.

**Pull request closed without merging**
