### PR TITLE
Support webkit gradients a bit better [issue 287]

### PR DESCRIPTION
**Pull request by sdhull**
See issue # 287.  This isn't a perfect solution but it's good for some simple cases.

Anything better might be infeasible.  The implementation could probably be a bit cleaner.  Sorry, I'm totally unfamiliar with SassScript.  I felt a bit like I was fumbling in the dark.  That said, it works fine for me.

https://github.com/chriseppstein/compass/issues/#issue/287

### CODE REVIEW

**Comment by sdhull** [comment]
What about the rest of this stuff?  Or do you want me to give you another pull request that doesn't include removing that non-ascii character?

**Comment by chriseppstein** [comment]
No need for a new pull request. The other commit looks good after reviewing it, but I need to sit down and understand it a little bit better before I merge it in.

**Comment by sdhull** [comment]
OK for sure. You could probably figure out a better way to do it, that was just a quick'n'dirty way I came up with prior to our release.

**Comment by chriseppstein** [comment]
Not sure what that means. Should I expect an update to this pull request?

**Comment by sdhull** [comment]
Sorry -- I guess that was confusing --  I was just bowing to your awesome work on Compass so far.  :)

Plus I was severely confused by pieces of the codebase, so I wasn't sure that I was achieving what I set out to achieve in an optimal way.  It totally gets the job done, but I figured you would know when you looked at it whether or not there was a better way to do it.  If not, then awesome!  If so, then pull it in and refactor, or describe the better way to me and I could try refactoring or whatever.

Just trying to recognize that you are more familiar with the codebase than I am.

**Comment by MyHealthTeams** [comment]
Say, are you still looking at this? I would love to get my office back to mainline compass and off my personal fork.

Thanks!
-Steve

**Comment by chriseppstein** [comment]
Yes. I will be doing a bunch of work on gradients soon and will address this at that time.

**Comment by chriseppstein** [comment]
Merged. Thanks!

**Pull request closed without merging**
