### PR TITLE
Sort sprites in map by file size

### PR DESCRIPTION
**Pull request by ai**
Currently sprites in map sort alphabetically. For most developers it is mean randomly. I think it will be better to sort sprites by file sizes, becuase then half of sprites will be loaded faster. Now we have some bad examples, for example http://static.groupon.ru/images/jobs-sdf196c2b3a.png very big background is in first position, but it only for decoration.

### CODE REVIEW

**Comment by chriseppstein** [comment]
@jetviper21 thoughts?

**Comment by scottdavis** [comment]
"half of sprites will be loaded faster" im curious to how true this is. The question i have it it necessary to features like this. The issue i have with this is with the bin packing method that is in the works sorts by width or height depending on layout. this is going to add a lot more "what if's" to the current roadmap. If you can prove that it truly does effect render time then im game but i think your going to find that its negligible unless your sprite files are enormous and in that case you may not want to sprite.

**Comment by scottdavis** [comment]
my main concern about spiriting large images is mostly browser memory usage.

**Comment by scottdavis** [comment]
see http://blog.vlad1.com/2009/06/22/to-sprite-or-not-to-sprite/ 3rd paragraph

**Comment by ai** [comment]
It will be helpful not only for big files. For example, in flags test files this patch put simple flags to top of file and half of flags will be loaded fatser too.

**Comment by ai** [comment]
Also if I remove big background from my sprite they will be contain very small and middle image. And load small icons faster will be better.

**Comment by ai** [comment]
Also, because small images will be together with this patch, it will join free area in right part of sprite map and reduce file image (of course, different will be small, but it we don’t lose anything).

**Comment by scottdavis** [comment]
im not against this but having to support 3+ ways of sprite layout is going to get to be a hassle thats why im being resistant. if this is needed maybe we should work out a way that people can extend the sprites to there liking?

**Comment by chriseppstein** [comment]
We'll have bin pack, horizontal pack, and vertical pack soon. This sounds like it's a bin pack competitor, yes? These three packs seem like enough to me but maybe I'm missing some finer point.

**Comment by scottdavis** [comment]
well horizontal pack actually solves this same problem

**Comment by ai** [comment]
I just think that file size sorting is better, that sort alphabetically. So I didn’t push another layout method, just try to make better current method.

**Comment by scottdavis** [comment]
So the other week I implemented horizontal packing which will solve your load smaller images first problem. So I think this implementation is unneeded moving forward https://github.com/chriseppstein/compass/commit/18c79f51a24a60e69bfce94b258cfaa723fb90b7

**Comment by ai** [comment]
Why horizontal packing solve my problem? After half size user will not see any full loaded images :).

**Comment by scottdavis** [comment]
Touché! If you apply the to master for vertical packing only I'll accept it

**Comment by ai** [comment]
Horizontal packing is in better_sprite_packing branch? Ok, I will create another pull request. Also, I think will be better to sort files in horizontal packing by image height, because it will join free bottom spaces.

**Comment by scottdavis** [comment]
Master

**Comment by scottdavis** [comment]
https://github.com/chriseppstein/compass/commit/b581d2e1a7720df5e812730a3232c4834b409498#L1R19

**Pull request closed without merging**
