### PR TITLE
Consider spacing on smart layout. Improves #1303 Fixes #718

### LINKED ISSUE #718: sprite with smart layout not support sprite-spacing?
When i use sprite-layout with smart, sprite-spacing not work, does it not support sprite-spacing with smart layout?

$icon-spacing: 5px !default;
$icon-layout:"smart";

### PR DESCRIPTION
**Pull request by camilonova**

### CODE REVIEW

**Comment by scottdavis** [comment]
Now we are getting there!

**Comment by camilonova** [comment]
@scottdavis great, so how can we make this happen?

**Comment by scottdavis** [comment]
You will need to create a unit test for this patch here: https://github.com/chriseppstein/compass/blob/master/test/units/sprites/layout_test.rb#L123

**Comment by camilonova** [comment]
@scottdavis I'll need help for the unit test.

**Comment by camilonova** [comment]
@scottdavis can I get a little help in here?

**Comment by chriseppstein** [comment]
I'm closing this PR because there's been too much change since it was initially submitted. Sorry, We're going to do better going forward. Hopefully, someone can resubmit the change against 1.0. Features should be submitted to the master branch, bug fixes to the stable branch.

**Comment by chriseppstein** [comment]
Should be on top of the changes coming in #1771.

**Comment by camilonova** [comment]
So sad.

**Comment by chriseppstein** [comment]
@camilonova I agree. I don't think it will be hard to clean this patch up. I'm trying to get this project back on track, and that meant focusing on some core things for a while. But now we're ready to receive PRs like this.

**Pull request closed without merging**
