### PR TITLE
Update to minitest5

### PR DESCRIPTION
**Pull request by movitto**
Rev 1: Rebased against master & updated

### CODE REVIEW

**Comment by scottdavis** [comment]
```
# Running:

................................................................................EEEEEEEE.EEEEE...............................................................................E.............................................................

Finished in 9.170385s, 25.6260 runs/s, 303.9131 assertions/s.

  1) Error:
SpritesImageTest#test_map:
Compass::SpriteException: No files were found in the load path matching "selectors/*.png". Your current load paths are: ./images
    /Users/sdavis/OSS/compass/cli/lib/compass/sprite_importer.rb:89:in `files'
    /Users/sdavis/OSS/compass/cli/lib/compass/sprite_importer.rb:94:in `sprite_names'
    /Users/sdavis/OSS/compass/cli/test/test_helper.rb:49:in `sprite_map_test'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:32:in `test_map'


  2) Error:
SpritesImageTest#test_image:
Compass::SpriteException: No files were found in the load path matching "selectors/*.png". Your current load paths are: ./images
    /Users/sdavis/OSS/compass/cli/lib/compass/sprite_importer.rb:89:in `files'
    /Users/sdavis/OSS/compass/cli/lib/compass/sprite_importer.rb:94:in `sprite_names'
    /Users/sdavis/OSS/compass/cli/test/test_helper.rb:49:in `sprite_map_test'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:32:in `test_map'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:36:in `test_image'


  3) Error:
SpritesImageTest#test_initialize:
Compass::SpriteException: No files were found in the load path matching "selectors/*.png". Your current load paths are: ./images
    /Users/sdavis/OSS/compass/cli/lib/compass/sprite_importer.rb:89:in `files'
    /Users/sdavis/OSS/compass/cli/lib/compass/sprite_importer.rb:94:in `sprite_names'
    /Users/sdavis/OSS/compass/cli/test/test_helper.rb:49:in `sprite_map_test'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:32:in `test_map'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:36:in `test_image'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:40:in `block in <class:SpritesImageTest>'


  4) Error:
SpritesImageTest#test_image_spacing:
Compass::SpriteException: No files were found in the load path matching "selectors/*.png". Your current load paths are: ./images
    /Users/sdavis/OSS/compass/cli/lib/compass/sprite_importer.rb:89:in `files'
    /Users/sdavis/OSS/compass/cli/lib/compass/sprite_importer.rb:94:in `sprite_names'
    /Users/sdavis/OSS/compass/cli/test/test_helper.rb:49:in `sprite_map_test'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:32:in `test_map'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:36:in `test_image'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:101:in `block in <class:SpritesImageTest>'


  5) Error:
SpritesImageTest#test_hover_should_find_image_by___or_-_in_file_name:
Compass::SpriteException: No files were found in the load path matching "selectors/*.png". Your current load paths are: ./images
    /Users/sdavis/OSS/compass/cli/lib/compass/sprite_importer.rb:89:in `files'
    /Users/sdavis/OSS/compass/cli/lib/compass/sprite_importer.rb:94:in `sprite_names'
    /Users/sdavis/OSS/compass/cli/test/test_helper.rb:49:in `sprite_map_test'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:32:in `test_map'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:56:in `block in <class:SpritesImageTest>'


  6) Error:
SpritesImageTest#test_image_repeat-x:
Compass::SpriteException: No files were found in the load path matching "selectors/*.png". Your current load paths are: ./images
    /Users/sdavis/OSS/compass/cli/lib/compass/sprite_importer.rb:89:in `files'
    /Users/sdavis/OSS/compass/cli/lib/compass/sprite_importer.rb:94:in `sprite_names'
    /Users/sdavis/OSS/compass/cli/test/test_helper.rb:49:in `sprite_map_test'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:32:in `test_map'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:36:in `test_image'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:85:in `block in <class:SpritesImageTest>'


  7) Error:
SpritesImageTest#test_neither,_uses_0:
Compass::SpriteException: No files were found in the load path matching "selectors/*.png". Your current load paths are: ./images
    /Users/sdavis/OSS/compass/cli/lib/compass/sprite_importer.rb:89:in `files'
    /Users/sdavis/OSS/compass/cli/lib/compass/sprite_importer.rb:94:in `sprite_names'
    /Users/sdavis/OSS/compass/cli/test/test_helper.rb:49:in `sprite_map_test'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:32:in `test_map'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:36:in `test_image'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:111:in `block in <class:SpritesImageTest>'


  8) Error:
SpritesImageTest#test_hover:
Compass::SpriteException: No files were found in the load path matching "selectors/*.png". Your current load paths are: ./images
    /Users/sdavis/OSS/compass/cli/lib/compass/sprite_importer.rb:89:in `files'
    /Users/sdavis/OSS/compass/cli/lib/compass/sprite_importer.rb:94:in `sprite_names'
    /Users/sdavis/OSS/compass/cli/test/test_helper.rb:49:in `sprite_map_test'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:32:in `test_map'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:36:in `test_image'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:52:in `block in <class:SpritesImageTest>'


  9) Error:
SpritesImageTest#test_image_position:
Compass::SpriteException: No files were found in the load path matching "selectors/*.png". Your current load paths are: ./images
    /Users/sdavis/OSS/compass/cli/lib/compass/sprite_importer.rb:89:in `files'
    /Users/sdavis/OSS/compass/cli/lib/compass/sprite_importer.rb:94:in `sprite_names'
    /Users/sdavis/OSS/compass/cli/test/test_helper.rb:49:in `sprite_map_test'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:32:in `test_map'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:36:in `test_image'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:95:in `block in <class:SpritesImageTest>'


 10) Error:
SpritesImageTest#test_no_parent:
Compass::SpriteException: No files were found in the load path matching "selectors/*.png". Your current load paths are: ./images
    /Users/sdavis/OSS/compass/cli/lib/compass/sprite_importer.rb:89:in `files'
    /Users/sdavis/OSS/compass/cli/lib/compass/sprite_importer.rb:94:in `sprite_names'
    /Users/sdavis/OSS/compass/cli/test/test_helper.rb:49:in `sprite_map_test'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:32:in `test_map'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:36:in `test_image'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:68:in `block in <class:SpritesImageTest>'


 11) Error:
SpritesImageTest#test_image_type_is_"no-repeat":
Compass::SpriteException: No files were found in the load path matching "selectors/*.png". Your current load paths are: ./images
    /Users/sdavis/OSS/compass/cli/lib/compass/sprite_importer.rb:89:in `files'
    /Users/sdavis/OSS/compass/cli/lib/compass/sprite_importer.rb:94:in `sprite_names'
    /Users/sdavis/OSS/compass/cli/test/test_helper.rb:49:in `sprite_map_test'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:32:in `test_map'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:36:in `test_image'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:79:in `block in <class:SpritesImageTest>'


 12) Error:
SpritesImageTest#test_image_repeat-y:
Compass::SpriteException: No files were found in the load path matching "selectors/*.png". Your current load paths are: ./images
    /Users/sdavis/OSS/compass/cli/lib/compass/sprite_importer.rb:89:in `files'
    /Users/sdavis/OSS/compass/cli/lib/compass/sprite_importer.rb:94:in `sprite_names'
    /Users/sdavis/OSS/compass/cli/test/test_helper.rb:49:in `sprite_map_test'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:32:in `test_map'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:36:in `test_image'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:90:in `block in <class:SpritesImageTest>'


 13) Error:
SpritesImageTest#test_offset:
Compass::SpriteException: No files were found in the load path matching "selectors/*.png". Your current load paths are: ./images
    /Users/sdavis/OSS/compass/cli/lib/compass/sprite_importer.rb:89:in `files'
    /Users/sdavis/OSS/compass/cli/lib/compass/sprite_importer.rb:94:in `sprite_names'
    /Users/sdavis/OSS/compass/cli/test/test_helper.rb:49:in `sprite_map_test'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:32:in `test_map'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:36:in `test_image'
    /Users/sdavis/OSS/compass/cli/test/units/sprites/image_test.rb:106:in `block in <class:SpritesImageTest>'


 14) Error:
SassExtensionsTest#test_font_files:
NoMethodError: undefined method `assert_nothing_raised' for #<SassExtensionsTest:0x0000010820b5a8>
    /Users/sdavis/OSS/compass/cli/test/units/sass_extensions_test.rb:152:in `test_font_files'

235 runs, 2787 assertions, 0 failures, 14 errors, 0 skips
rake aborted!
Command failed with status (1): [ruby -I"lib:lib:test" -I"/Users/sdavis/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib" "/Users/sdavis/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/rake_test_loader.rb" "test/integrations/compass_test.rb" "test/integrations/sprites_test.rb" "test/units/actions_test.rb" "test/units/caniuse_test.rb" "test/units/command_line_test.rb" "test/units/compass_util_test.rb" "test/units/compiler_test.rb" "test/units/configuration_test.rb" "test/units/regressions_test.rb" "test/units/sass_extensions_test.rb" "test/units/sass_extenstions/gradients_test.rb" "test/units/sprites/engine_test.rb" "test/units/sprites/image_row_test.rb" "test/units/sprites/image_test.rb" "test/units/sprites/images_test.rb" "test/units/sprites/importer_test.rb" "test/units/sprites/layout_test.rb" "test/units/sprites/row_fitter_test.rb" "test/units/sprites/sprite_command_test.rb" "test/units/sprites/sprite_map_test.rb" "test/units/watcher/compiler_test.rb" "test/units/watcher/project_watcher_test.rb" "test/units/watcher/watch_test.rb" ]
/Users/sdavis/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/sdavis/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
```

**Comment by movitto** [comment]
@scottdavis updated, believe I got everything, shout out if there is anything else

**Comment by scottdavis** [comment]
Thanks ill look over it in a bit

**Comment by chriseppstein** [comment]
Can we get this rebased and resubmitted against stable?

**Comment by scottdavis** [comment]
@chriseppstein I don't think that is necessary it was already rebased against master a few days ago and should only need a minor rebase for it to be mergeable.

**Pull request closed without merging**
