### PR TITLE
New Flexbox Mixins

### PR DESCRIPTION
**Pull request by cimmanon**
New mixins that support all 3 Flexbox implementations (see: https://github.com/chriseppstein/compass/issues/921).  There is a variable name conflict with the old "box" collection:  `$flexbox-support`.  I went with naming the support variables after the display property that goes along with it since the year thing might be a little confusing (especially since some articles refer to the Mar 2012 spec as _2011_):
- $flex-support (Sept 2012)
- $flexbox-support (Mar 2012)
- $box-support (July 2009)

Examples will be in a later pull request.

### CODE REVIEW

**Comment by frapontillo** [comment]
`ms` and `o` prefixes should be inverted, [per specification](http://compass-style.org/reference/compass/css3/shared/#mixin-experimental-value), in `$flex-support`, `$flexbox-support`, `$box-support`.
Please see [my comment on issue #921](https://github.com/chriseppstein/compass/issues/921#issuecomment-15585809).

**Comment by cimmanon** [comment]
The `experimental()` mixin I'm depending on uses this order:  moz, webkit, ms, o, khtml, standard.  See [this commit](https://github.com/chriseppstein/compass/commit/634f206336fdf7732882c57e2e0eab33b97052b1) to the master branch and https://github.com/chriseppstein/compass/issues/1000 for the reasoning behind the change in prefix order.

**Comment by mirisuzanne** [comment]
I'm ready to pull this in, but it should have docs and an entry in the changelog. Can you do that? Check the [documentation readme](https://github.com/chriseppstein/compass/blob/stable/doc-src/README.markdown) for more on how docs are generated.

**Comment by cimmanon** [comment]
Yes, I'll get that done this weekend.

**Comment by cimmanon** [comment]
I'm not able to test to make sure the examples/docs work since I can't get bundler to do its job (ruby_prof is failing to compile).

**Comment by mirisuzanne** [comment]
Thanks! We can make adjustments still as needed.

**Comment by scottdavis** [comment]
Docs do not build with this merge:

```
Loading site data…
Compiling site…
      update  [0.00s]  output/blog/atom.xml
      update  [0.02s]  output/CHANGELOG/index.html

Captain! We’ve been hit!

Message:

Haml::SyntaxError: Illegal nesting: content can't be both given on the same line as %div and nested within it.

Compilation stack:

  - [item]   /examples/compass/css3/flexbox/_flexbox/ (rep default)

Stack trace:

  0. item /examples/compass/css3/flexbox/_flexbox/ (rep default):2
  1. /Users/sdavis/.rvm/gems/ruby-1.9.3-p392/gems/haml-3.1.7/lib/haml/parser.rb:341:in `tag'
  2. /Users/sdavis/.rvm/gems/ruby-1.9.3-p392/gems/haml-3.1.7/lib/haml/parser.rb:359:in `div'
  3. /Users/sdavis/.rvm/gems/ruby-1.9.3-p392/gems/haml-3.1.7/lib/haml/parser.rb:185:in `process_line'
  4. /Users/sdavis/.rvm/gems/ruby-1.9.3-p392/gems/haml-3.1.7/lib/haml/parser.rb:148:in `parse'
  5. /Users/sdavis/.rvm/gems/ruby-1.9.3-p392/gems/haml-3.1.7/lib/haml/engine.rb:124:in `initialize'
  6. /Users/sdavis/.rvm/gems/ruby-1.9.3-p392/gems/nanoc-3.4.3/lib/nanoc/filters/haml.rb:23:in `new'
  7. /Users/sdavis/.rvm/gems/ruby-1.9.3-p392/gems/nanoc-3.4.3/lib/nanoc/filters/haml.rb:23:in `run'
  8. /Users/sdavis/.rvm/gems/ruby-1.9.3-p392/gems/nanoc-3.4.3/lib/nanoc/base/result_data/item_rep.rb:348:in `filter'
  9. /Users/sdavis/.rvm/gems/ruby-1.9.3-p392/gems/nanoc-3.4.3/lib/nanoc/base/compilation/item_rep_proxy.rb:47:in `filter'
  ... 32 more lines omitted. See full crash log for details.

```

**Comment by mirisuzanne** [comment]
The local doc setup has been fixed, and I got the flexbox docs running. They're a bit ugly at the moment, though. @cimmanon can you take a look at that? See if you can get them working locally, and clean them up a bit? I had to run `bundle install` and then `./bin/nanoc aco`.

**Comment by cimmanon** [comment]
Trying to get the docs running broke quite a few things on my virtual box.  A library Git depends on is missing and I can't build a gem for Compass anymore.  I'm stuck until I can get my husband to fix it for me.

**Pull request merged**
