### PR TITLE
Add selection mixin

### PR DESCRIPTION
**Pull request by corroded**
As mentioned [here](https://github.com/chriseppstein/compass/pull/1007). Sorry for the wrong PR. This one is for the master branch.

### CODE REVIEW

**Comment by mirisuzanne** [comment]
Looks great! Thanks for helping out! Can you add documentation and tests for it as well, please?

See the [website](http://compass-style.org/help/tutorials/contributing/) and [docs readme](https://github.com/chriseppstein/compass/blob/stable/doc-src/README.markdown) for more details on how to do that.

**Comment by corroded** [comment]
No problem! Happy to be able to contribute to my favorite tool! I'll try to
learn the ropes in setting up the docs so I can create some documentation.
Not sure about the tests though, do I just add the generated stylesheet
there? How do I test? The website link seems a bit incomplete - or maybe I
missed it?

**Comment by mirisuzanne** [comment]
Writing tests is fairly simple: 
1. Go to `test/fixtures/stylesheets/compass/`and you'll see there's a folder for sass, a folder for css, and a folder called "saved". 
2. Write your test in the Sass directory (you can see there how others are done).
3. [run the tests](http://compass-style.org/help/tutorials/contributing/#running-tests). 
4. The first time you do, it will fail, but the output can be found in the "saved" directory. If it looks good, copy that file into "css" and you're all set. (Doesn't hurt to run tests one last time and make sure they pass.)

**Comment by corroded** [comment]
Just wanted to update that I am on this. Just a bit busy at the moment but will definitely update the tests and docs as soon as I can :)

**Comment by chriseppstein** [comment]
This is why we don't accept patches until after the docs and tests are present :-1:

**Comment by corroded** [comment]
Shi---I completely forgot about this! Sorry, I do apologize for this. I had some tests going on but (probably) stopped when I saw the commits for this one https://github.com/chriseppstein/compass/pull/1007. 

I can still work on this if it is still needed. Again, I apologize :(  If ever it is still needed, do I just add to this PR or the PR 1007?

**Pull request merged**
