### PR TITLE
Fixes #449.  Accept and honor offsets in selectors

### LINKED ISSUE #449: all-*-sprites  should accept and honor offsets
The `sprite` mixin allows you to supply and x and y offset.  `all-*-sprites` uses the `sprite` mixin internally, but doesn't allow you to specify offsets.

And, a closely related issue.  If you'd like me to break these into two tickets, let me know.
Offsets are not honored when compass generates :active, :hover and :target selectors from _active.png, _hover.png and _target.png images.  Compass will also generate excessive selectors.  

See https://gist.github.com/1057445 for an example of both issues.

Edit: I'm using the rails31 branch

### PR DESCRIPTION
**Pull request by caged**
I think I've got it sorted now.

### CODE REVIEW

**Comment by scottdavis** [comment]
i think this is a duplicated of https://github.com/chriseppstein/compass/pull/450

**Comment by caged** [comment]
Odd, I didn't see the other pull request earlier.  It looks like there is some duplication, but the other pull request didn't go far enough.  It didn't include the `sprites` and `sprite` method among other things.

**Comment by scottdavis** [comment]
Noted I'll get it merged in and working thanks!

Scott Davis

**Comment by MarioRicalde** [comment]
If this is merged, lets close the pull request ;)

**Comment by scottdavis** [comment]
@kuroir all done cupcake

**Comment by MarioRicalde** [comment]
Thanks hun.

**Comment by caged** [comment]
Which commit was this fixed in?  Specifically in reference to this comment - https://github.com/chriseppstein/compass/pull/454#issuecomment-1493626.

**Comment by scottdavis** [comment]
@caged it got mixed up in this massive merge https://github.com/chriseppstein/compass/commit/38cf0e571b92a079fb101f60559046534d576125 mostly because i was tired

**Comment by caged** [comment]
That's cool.  Looks like you got it all.

**Pull request closed without merging**
