### PR TITLE
Use the new Docker queue

### PR DESCRIPTION
**Pull request by joshk**
faster better stronger

### CODE REVIEW

**Comment by chriseppstein** [comment]
Thanks, @joshk! Does this pave the way for enabling windows builds by any chance?

**Comment by joshk** [comment]
Not yet sorry, I might have some news to share in a couple of weeks, but not yet sorry.

**Comment by chriseppstein** [comment]
Thank you. :heart: We got bit by some bad windows bugs in our latest releases. :cry:

**Comment by joshk** [comment]
I hear ya

adding Windows support is a huge undertaking, especially learning the toolchain and providing support

hopefully good news to follow soon

**Pull request merged**
