### PR TITLE
Fix broken `text-shadow` syntax

### PR DESCRIPTION
**Pull request by joeyhoer**
A small bug, the `@` for the `else` statement was omitted, and causing the else statement to always be evaluated.

Proposed fix for #958

### CODE REVIEW

**Comment by mirisuzanne** [comment]
Thanks! This looks like a great fix, but we'll need the tests updated as well. Can you take a look at that and update the pull request?

**Comment by joeyhoer** [comment]
AFIK, the current tests, when used with this commit, will produce the expected/valid CSS.

However, the current tests, when run through the current code will produce unexpected/invalid syntax due to the bug.

I've run the tests and everything appears to be in working order.

**Comment by mirisuzanne** [comment]
The way compass tests work, you need to update what is expected under `test/fixtures/stylesheets/compass/css/text_shadow.css`. Currently it shows:

``` css
.multiple-text-shadows-with-spread {
  text-shadow: 4px 4px 10px #444444, 4px 4px 10px 1px #444444, 2px 2px 5px #222222, 2px 2px 5px 3px #222222;
  text-shadow: 4px 4px 10px 1px #444444, 4px 4px 10px 1px #444444, 2px 2px 5px 3px #222222, 2px 2px 5px 3px #222222; }
```

That is the incorrect output - due to the bug. Clearly someone wasn't paying attention when they wrote that test. Update that to match the correct output, and everything should work.

**Comment by chriseppstein** [comment]
Thanks. This file got basically re-written for 1.0 and this bug is no longer present.

**Pull request closed without merging**
