### PR TITLE
loosen listen version

### PR DESCRIPTION
**Pull request by jjb**
see discussion in https://github.com/chriseppstein/compass/pull/1177

### CODE REVIEW

**Comment by thibaudgg** [comment]
I think event set  `~> 1.0` is good, only `2.0` will change the api a little and remove ruby 1.8 support.

**Comment by scottdavis** [comment]
change this to `~> 1.0` and ill merge it

**Comment by jjb** [comment]
@scottdavis done

**Comment by jjb** [comment]
(n.b. if you want to ensure supporting 1.8, it should be `~> 1.0.0`)

**Comment by scottdavis** [comment]
I'm not ignoring this. i just updated to listen 1.0.3 manualy and am now getting an error in the test suite. So i need to see what changed from 0.9.x -> 1.0

**Comment by scottdavis** [comment]
```
Failing Scenarios:
cucumber features/command_line.feature:182 # Scenario: Watching a project for changes
```

```
No such file or directory - /tmp/last_result.compass_test.txt (Errno::ENOENT)
      ./features/step_definitions/command_line_steps.rb:93:in `read'
      ./features/step_definitions/command_line_steps.rb:93:in `/^I shutdown the other process$/'
      features/command_line.feature:190:in `And I shutdown the other process'
    Then a css file tmp/layout.css is reported identical\                      # features/step_definitions/command_line_steps.rb:154
```

**Pull request closed without merging**
