### PR TITLE
Adds normalize.css framework.

### PR DESCRIPTION
**Pull request by ghost**
This is a plain copy of [normalize.css](https://github.com/necolas/normalize.css/). It would be great to have this as an alternative to a css reset.

### CODE REVIEW

**Comment by scottdavis** [comment]
I would actually prefer something like this remain an extension for maintainablity sake

**Comment by mirisuzanne** [comment]
+1 for a plugin

**Comment by ghost** [comment]
Alright then, here we go: [https://github.com/jroettger/compass-normalize-plugin](compass-normalize-plugin). I am still working on the documentation, but it's working and everything.

**Comment by scottdavis** [comment]
cool

**Pull request closed without merging**
