### PR TITLE
rewrote contrasted utility to not rely on a lightness threshold. Intstea...

### PR DESCRIPTION
**Pull request by bluesaunders**
...d it caluclates brightness of the color and compares to the given background color.

This pull request is for issue #1051.

### CODE REVIEW

**Comment by mirisuzanne** [comment]
Thanks!

**Comment by chriseppstein** [comment]
This is a good patch but it breaks backwards compatibility :(

**Comment by mirisuzanne** [comment]
Should I give these mixins new names, and bring back the old ones with a deprecation warning? I think it's a change that really should be made, and the question is just upgrade path.

**Comment by chriseppstein** [comment]
Ideally, we would have the function generate deprecation messages if the old arguments are passed. And in the case where they are using the old parameters, we would leave the output unchanged. They could silence the deprecation warnings by updating their stylesheets to use the new API.

We should also document this change in the [CHANGELOG](https://github.com/bluesaunders/compass/blob/stable/doc-src/content/CHANGELOG.markdown) and provide the rationale for the change and examples of how to update existing code to use the new API.

**Comment by mirisuzanne** [comment]
Sounds good. @bluesaunders feel free to work on that if you are interested, otherwise I'll try to get to it soon.

**Pull request merged**
