### PR TITLE
Stable

### PR DESCRIPTION
**Pull request by lyuba**
Support of the bold and italic in the @font-face discussed here:
http://groups.google.com/group/compass-users/browse_thread/thread/38ca3792b07ff80a/cd2c413ea6cec2a3?lnk=gst&q=font+face+bold#cd2c413ea6cec2a3

### CODE REVIEW

**Comment by mirisuzanne** [comment]
Looks good! Though I'd prefer $weight and $style defaulting to false rather than normal. I don't see enough reason to change what the default output has been.

**Comment by lyuba** [comment]
Done :)

**Comment by scottdavis** [comment]
@ericam can you approve this for merge? doing some house cleaning

**Comment by MarioRicalde** [comment]
Everything looks ok with this commit. The documentation was added and no extra css is generated with this updated unless explicitly required.

Safe Merge.

**Comment by scottdavis** [comment]
im not going to step on eric's toes this is his dept.

**Comment by mirisuzanne** [comment]
Yeah, sorry, I just got overwhelmed at work.

This looks great to me. Thanks @lyuba. I haven't had the time to confirm the docs and the tests, but if someone else can do that and merge it, this has my approval.

**Comment by scottdavis** [comment]
np thanks eric ill merge it in

**Comment by scottdavis** [comment]
done : https://github.com/chriseppstein/compass/commit/ac43297822f9c3dd9cd87817af0c3b65640b404d

**Comment by lyuba** [comment]
Wow, great, my first commit to opensource :)

**Pull request closed without merging**
