### PR TITLE
if manifest_file not exists, discover :all

### PR DESCRIPTION
**Pull request by tka**

### CODE REVIEW

**Comment by tka** [comment]
need test case and update docs

**Comment by scottdavis** [comment]
also would you mind redoing this against master?

**Comment by tka** [comment]
@scottdavis I think the master branch can use the same patch, should I send another pull request for master branch?

**Comment by scottdavis** [comment]
Stable is always the current stable. I don't think we are planing a bug fix to the 11.x and are moving forward with 0.12.x so yes please do this against master

**Comment by tka** [comment]
@scottdavis ok, I understand now. thank you

**Pull request closed without merging**
