### PR TITLE
float-reset updated

### PR DESCRIPTION
**Pull request by adamstac**
Updated the code to what hagenburger and I commented about in my fork. See this pull request for more details: https://github.com/chriseppstein/compass/issues#issue/245
- Adam

### CODE REVIEW

**Comment by scottdavis** [comment]
probably want this to be against master and not stable 250 commits is alot =) I made this mistake once

**Comment by chriseppstein** [comment]
I've merged this change into master. I moved the mixin in the float module because you only need it when you're using the other mixins in that module.

**Comment by chriseppstein** [comment]
I've merged this change into master. I moved the mixin in the float module because you only need it when you're using the other mixins in that module.

**Comment by chriseppstein** [comment]
https://github.com/chriseppstein/compass/commit/9b0967eb474c791ff5be7b0510cfdb5a01db6c46

**Pull request closed without merging**
