### PR TITLE
Changed the descriptions of the sin, cos, and tan to be more descriptive.

### PR DESCRIPTION
**Pull request by tyrinslys**
Changed the descriptions of the sin, cos, and tan to be more descriptive.

This is the first pull request that I have sent, let me know if there are problems.

### CODE REVIEW

**Comment by MarioRicalde** [comment]
Awesome. This clears the misunderstandings that were going on with people passing unitless attr's to the function expecting it to be degrees.

**Comment by scottdavis** [comment]
cherry-picked into master thanks!  https://github.com/chriseppstein/compass/commit/d8e43bfdd7f43796d52f82cacbe92dc379beb44a

**Comment by tyrinslys** [comment]
Now that this is cherry-picked I can delete this remote branch right. I am not familiar with github so I just want to be sure. If there is some other workflow I should be using let me know.

**Comment by scottdavis** [comment]
yep. you did everything perfectly except making the pull request against stable instead of master =)

**Pull request closed without merging**
