### PR TITLE
Add `compass preview` command.

### PR DESCRIPTION
**Pull request by uu59**
Hi :)

I added `compass preview` command.
I think this is useful for quick reference, quick check compile result, and so on.
How do you think?

### CODE REVIEW

**Comment by Saturate** [comment]
I don't get why you wound not use `compass compile`, seems a bit redundant? You still get the errors, and is just as quick?

**Comment by Anahkiasen** [comment]
Plus I don't think above 50 lines it would  be comfortable to preview in the terminal.

**Comment by uu59** [comment]
`compass compile` is require to run `compass create`. 

But my use cases are:
1. I'm browsing webpage that explain some Compass technique.
   If `compass preview` command exists, I copy-and-paste his code snippet to a new file (/tmp/copied.scss) and run `compass preview /tmp/copied.scss | less` to see what he said.
   I think this is helpful for a CSS professional but Compass newbie  (including me). 
2.  I'm editing Sass file with Vim (or any editor). I wanna see compiled CSS from this situation.
   `compass preview` provides dead simple compiling feature that means I can create Vim plugin easily such as press `<C-r>` to  see compiled CSS in the editor.

My point is that:
I need simple to compile command such as `scss`, `sass`, and `coffee`. `compass compile` is too complex to use for above situations.

**Comment by MoOx** [comment]
Maybe you should just ask what `compass create` create, which is required to make `compass compile` possible. Maybe just a `.sass-cache`dir ?

**Comment by uu59** [comment]
I investigated `compass compile` options.
But `--sass-dir SRC_DIR` receive a directory, not just a sass file. And `--css-dir CSS_DIR` is too.

My needs is that compile single sass file into single css file(or output to STDOUT). `compass compile` can't do it I think.

Directory to directory compiling is almost enough for a "project", but `compass preview` provides for more relaxed usage. I believe it could be helpful.

P.S. If you can't agree that, feel free to reject this pull request :smiley:

**Comment by piouPiouM** [comment]
You can simply precise the current directory as Sass and CSS directories:

```
compass compile --sass-dir . --css-dir . test.scss
```

In this example, a `test.css` file will be created.

**Comment by uu59** [comment]
Ah... sorry guys, I found a way for my success.

```
$ scss `compass imports` /path/to/foo.scss
```

That command is simple enough to fit to me.

Thanks to replies.

**Pull request closed without merging**
