### PR TITLE
Add <main> tag as a new html5 block level element

### PR DESCRIPTION
**Pull request by daphotron**
See Issue #1335

### CODE REVIEW

**Comment by mirisuzanne** [comment]
Thanks for the patch! But currently this is breaking the tests. Do you mind updating the tests and re-submitting?

**Comment by daphotron** [comment]
@ericam Oh definitely! :) So I received this error `compass/test/helpers/test_case.rb:42:in `setup': wrong number of arguments (2 for 0) (ArgumentError)` after running `bundle exec rake test features` but I found that by commenting out the setup block as mentioned in this closed pull request https://github.com/rubiii/compass/commit/e5d9fdff8e04916856889280609d82173d0d7d75 allowed the bundle test to run. 

After getting that hurdle over with...I wasn't sure how to recompile the css files inside the test folder. I tried running `compass compile --force` and other such commands inside individual folders inside `compass/test/fixtures/stylesheets` but noticed that they were 1) going to a tmp directory and 2) not picking up the latest changes I made to the `html5-block` variable. Forgive my noobness but I couldn't find any good docs about editing tests other than http://compass-style.org/help/tutorials/contributing/#running-tests and the docs made it seem that by running the test, the test would be "changing the expected css output to make the test pass". Is there a command I'm missing or more documentation on how to update the stylesheet tests?

**Comment by mirisuzanne** [comment]
I'm not sure if there are ruby unit tests that need to be updated, but for the css output tests, you have to manually change the expected output. When you `rake test` - the tests are compiled into the `saved` folder and then compared to the expected output in the `css` folder. You need to make sure the saved output is correct, and then update the expected css to match. Then run the tests again to make sure they pass.

**Comment by chriseppstein** [comment]
This was implemented in 32b3a49f55b06691dcdd9f135ba2a95184a17ca9.

**Pull request closed without merging**
