### PR TITLE
fix transparent gradients

### PR DESCRIPTION
**Pull request by curzonj**
This is by no means the best way to solve the problem, just the only
that I found on google.

https://gist.github.com/1722819

I need this so that I can include the twitter bootstrap files into my application.css file.

### CODE REVIEW

**Comment by scottdavis** [comment]
The more i look at this the more im thinking this is the wrong approach sass really needs a "transparent" color

**Comment by mwawrusch** [comment]
+1000000 - just wasted a couple hours on this and similar issues.

**Comment by chriseppstein** [comment]
I have a patch for this that preserves the transparent keyword in the output.

**Comment by chriseppstein** [comment]
But thank you very much for your patch!

**Pull request closed without merging**
