### PR TITLE
Color grid background with gradients for 0 gutters grids

### PR DESCRIPTION
**Pull request by tsi**

### CODE REVIEW

**Comment by tsi** [comment]
Will solve issues like https://github.com/ericam/susy/issues/155

**Comment by mirisuzanne** [comment]
This looks good to me. I suppose the other option is recognizing 0-gutters, and alternating columns. If no one has a problem with this or a strong argument for the other, I'll pull it in as-is.

**Comment by scottdavis** [comment]
test case update?

**Comment by chriseppstein** [comment]
merged to master.

**Pull request closed without merging**
