### PR TITLE
Support Ruby 2.2.0

### PR DESCRIPTION
**Pull request by tonytonyjan**
ref: https://bugs.ruby-lang.org/issues/10314 and  #1902

### CODE REVIEW

**Comment by jurriaan** [comment]
👍

**Comment by davegson** [comment]
:+1:

**Comment by acrogenesis** [comment]
:+1: on merge

**Comment by nazarok** [comment]
The request will be merged?

**Comment by marczking** [comment]
:+1:

**Comment by rosenfeld** [comment]
:+1:

**Comment by i1t** [comment]
:+1:

**Comment by fake-or-dead** [comment]
:+1:

**Comment by d0minicw0ng** [comment]
:+1: It would be nice if this gets merged as soon as possible.

**Comment by yuku** [comment]
:+1:

**Comment by Delius** [comment]
:+1:

**Comment by saki7** [comment]
:+1:

**Comment by zedtux** [comment]
:+1:

**Comment by domoritz** [comment]
:+1:

**Comment by imgarylai** [comment]
:+1:

**Comment by dgpokl** [comment]
:+1:

**Comment by phoet** [comment]
@chriseppstein could you take a look at merging this?

**Comment by scottdavis** [comment]
let me update travis for ruby 2.2 then ill cut a new minor release

**Comment by phoet** [comment]
@scottdavis thx, awesome :heart:

**Comment by phoet** [comment]
@scottdavis thx, awesome :heart:

**Comment by scottdavis** [comment]
can't cut a 1.0.2 until chris gives me rubygems access to the 2 new subgems so its in git and tagged for now

**Comment by nazarok** [comment]
thx

**Comment by scottdavis** [comment]
1.0.2 is in the wild

**Comment by mhoran** [comment]
We're getting the following after upgrading:

``` bash
[mhoran@tacosaurus] ~/kitchensurfing% rails s
/Users/mhoran/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/compass-1.0.2/lib/compass/version.rb:37:in `read': No such file or directory @ rb_sysopen - /Users/mhoran/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/compass-1.0.2/lib/compass/../../VERSION_NAME (Errno::ENOENT)
```

The file `VERSION_NAME` indeed seems not to exist.

**Comment by mhoran** [comment]
Inspecting `lib/compass/generated_version.rb` reveals the following:

``` ruby
module Compass
  # This file intentionall does nothing.
  # The compass build scripts put the release VERSION constant here.
end
```

**Comment by rosenfeld** [comment]
I can confirm the new issue

**Comment by rosenfeld** [comment]
Pointing to the stable branch in the Gemfile seems to work though:

``` ruby
gem 'compass', github: 'Compass/compass', branch: 'stable'
```

**Comment by mhoran** [comment]
Fixed in 1.0.3.

**Comment by davegson** [comment]
thanks guys! works like a charm :)

**Pull request merged**
