### PR TITLE
TypeError: can't convert Sprockets::StaticAsset into String

### PR DESCRIPTION
**Pull request by comboy**
So I got an error like:

TypeError: can't convert Sprockets::StaticAsset into String

While trying to serve css.  I'm not able to provide easy steps to reproduce. 

Included fix works for me, but you probably can understand better what is going on there, maybe these Sprockets::StaticAsset objects should not be getting there in the first place.

### CODE REVIEW

**Comment by scottdavis** [comment]
more details rails version, sprockets version?

**Comment by comboy** [comment]
rails 3.1.1
sprockets 2.0.2

**Comment by scottdavis** [comment]
ok ill get this patched in the railtie

**Comment by lankz** [comment]
any update on this?

**Comment by scottdavis** [comment]
sorry ive been super busy what is the scss that is triggering this im trying to recreate the problem

**Comment by yorkxin** [comment]
Same here.

Rails 3.1.1 with Sprockets 2.0.3 and Compass 0.12.alpha.0.ebd758a (master)

The problem can be re-produced by requesting the sprite helper to inject image dimension, like this: (modified from example in [Spriting with Compass](http://compass-style.org/help/tutorials/spriting/) )

```
@import "icon/*.png";

.actions {
  .new    { @include icon-sprite(new, $dimensions: true);    }
}
```

Then you'll get

```
can't convert Sprockets::StaticAsset into String
```

exception.

**Comment by scottdavis** [comment]
is this a problem even in the latest release? im using this in production with no issues.

**Comment by yorkxin** [comment]
No, it doesn't work, either.

I was using `sass-rails 3.1.4` and tried `sass-rails 3.1.5.rc2`, with master branch of compass' repository.  Either of them does work.

**Comment by scottdavis** [comment]
You going to have to give me a repo that replicates the problem I can't seem to make it trigger

**Comment by scottdavis** [comment]
d335855

**Comment by yorkxin** [comment]
It works now!  Thanks!

**Pull request closed without merging**
