### PR TITLE
Update to minitest 5

### PR DESCRIPTION
**Pull request by movitto**
Greetings, we're looking to fix some packages in Fedora the were broken by a recent update to minitest (now at 5.3.1).

compass was one of the gems that was broken due to it's dependency on the old API.

http://koji.fedoraproject.org/koji/packageinfo?packageID=10224

I went through and patched the source to work against the new API and am sending a PR for hopeful inclusion upstream.

Thank you for your time.

### CODE REVIEW

**Comment by movitto** [comment]
Build after patch is applied:

http://koji.fedoraproject.org/koji/taskinfo?taskID=7041047

**Comment by scottdavis** [comment]
I hate to be "that" guy but i can't merge this into stable to much has diverged between stable and master to make it in cleanly upstream

**Comment by movitto** [comment]
@scottdavis rebased this PR against the latest stable. Would you rather me rebase / resubmit against master?

**Comment by scottdavis** [comment]
Master please

**Comment by movitto** [comment]
Rebased against master / updated in #1722. Closing this.

**Pull request closed without merging**
