### PR TITLE
added always even positions to the smart-layout with an extra padding of 2

### PR DESCRIPTION
**Pull request by afewyards**
Added the always even positions to the smart layout to fix the ghosting of retina sprites. they get divided and if there positions is odd the position will be not on a int. This will fix that

### CODE REVIEW

**Comment by scottdavis** [comment]
I like the thought behind this patch, but it needs the test cases updated before i accept it.

**Comment by afewyards** [comment]
ahh, ok will do that when I got more time.. prob somewhere later this week.

**Comment by chriseppstein** [comment]
ping?

**Comment by afewyards** [comment]
ok, took a while but I updated the test cases and altered the sprite generation a bit to have a better/good result.

**Comment by afewyards** [comment]
I see that "rcov" fails in the 1.9+ builds.. as that needs to be converted into "simplecov" that is not part of this pull request.

**Comment by chriseppstein** [comment]
I'm closing this PR because there's been too much change since it was initially submitted. Sorry, We're going to do better going forward. Hopefully, someone can resubmit the change against 1.0. Features should be submitted to the master branch, bug fixes to the stable branch.

@scottdavis has refactored sprites considerably, we need to rebase this work to take his recent changes (soon to land on master) into account.

**Comment by chriseppstein** [comment]
Should be on top of the changes coming in #1771.

**Pull request closed without merging**
