### PR TITLE
Changed the header of Compass

### PR DESCRIPTION
**Pull request by JamesVanWaza**

### CODE REVIEW

**Comment by scottdavis** [comment]
We have already merged in a notice about support I think one that removes documentation links is a bit extreme.

**Comment by JamesVanWaza** [comment]
@scottdavis the reason I did that is so that the issues can no longer be added, is there a way for you to close all issues?

**Comment by scottdavis** [comment]
I don't think closing the issues gains anything. It's an active record of known issues in case someone does have an issue if they are running compass in a ongoing or legacy project.

**Comment by JamesVanWaza** [comment]
Ok. @scottdavis Then make the Header Larger so that it is easily seen.

**Comment by scottdavis** [comment]
i changed the site description header.

**Pull request closed without merging**
