### PR TITLE
Added in a 'Possible Values: none' to the documentation for box-shadow, ...

### PR DESCRIPTION
**Pull request by RichardLitt**
...as per ticket #102 which was never closed.

### CODE REVIEW

**Comment by RichardLitt** [comment]
I should say never resolved. The ticket itself was closed.

**Comment by chriseppstein** [comment]
`none` is a legal value for the box shadow property. I feel like the existing documentation sufficiently describes the arguments accepted and adding this makes it feel like other values are not allowed.

**Comment by chriseppstein** [comment]
But thank you for making the patch.

**Comment by RichardLitt** [comment]
Sounds good. Thanks.

**Pull request closed without merging**
