### PR TITLE
sort sprites alphabetically

### PR DESCRIPTION
**Pull request by krisbulman**
This is basically @hagenburger's https://github.com/hagenburger/compass/commit/c472664b55269547de7231b7788ffb11c065e3ca on this issue #1002 as a pull request, with the optional fallback to width removed, as I don't think it's necessary.

### CODE REVIEW

**Comment by scottdavis** [comment]
We need to come up with another approach for this changing the sorting to alpha doesn't make sense for the people that specifically asked for width sorting. Sorting instead needs to be changed into something that is configurable.

**Comment by scottdavis** [comment]
What nico had was acceptable as a patch I'm not sure why he never sent in a PR. There are reasons for sorting by width and file size so that you smaller images become available in progressive loading in browsers that support it.

**Comment by hagenburger** [comment]
@scottdavis just came back from my two months China trip few hours ago. What I did worked quite well, but without any test. I would have a look at it again at the weekend.

**Comment by scottdavis** [comment]
No biggie im cooking up something now that may be more configurable

**Comment by scottdavis** [comment]
besides alpha sorting and size sorting what else should be offered.

**Comment by notethis** [comment]
What's the status of sorting by alpha?

**Comment by sbdev** [comment]
This sort-by parameter would be a great way to optimize css dowloads.
CSS files that don't use newly added icons currently are likely to require new offsets and therefore require version bump and re-download by all users :-(

https://github.com/chriseppstein/compass/commit/520c950f7d9a9bf7d5cf99842e898feec8aa7364
Why it didn't make it into 0.12.2?

**Comment by scottdavis** [comment]
Mostly because 0.12.2 was released way before that change was made

**Comment by sbdev** [comment]
oops didn't realize 0.12.2 is one-year old (06/24/2012). Sorry!
Any plan for a 0.12.3?

**Pull request closed without merging**
