### PR TITLE
Add more math functions and unite them with Trig

### PR DESCRIPTION
**Pull request by silvenon**
The first commit adds more math functions and groups them with trigonometry functions as `Math` module, i.e. `Trig` is merged into `Math`.

The second commit adds those span elements around some arguments in helpers which are missing them. I know it's not really related to math functions, but I wanted to squeeze those in also :)

### CODE REVIEW

**Comment by chriseppstein** [comment]
Can you add tests for the new functions like we have for the trig functions: https://github.com/chriseppstein/compass/blob/stable/test/units/sass_extensions_test.rb#L67-82

**Comment by silvenon** [comment]
Unfortunately, I can't run them right now because of some gem issue I have, I hope they pass.

**Comment by chriseppstein** [comment]
Hop into IRC today and we'll sort that out.

**Comment by silvenon** [comment]
Btw, trig tests have already been fixed in [this](https://github.com/chriseppstein/compass/pull/734) pull request.

**Pull request merged**
