### PR TITLE
Webkit supports box-sizing

### PR DESCRIPTION
**Pull request by VinceCgto**

### CODE REVIEW

**Comment by Anahkiasen** [comment]
That's not how prefixes are handled anymore so that shouldn't be necessary, check the master branch.

**Comment by VinceCgto** [comment]
Ah yes, I see.

Still needs to be changed somewhere, though I'm not familiar with the current handling of prefixes.

**Comment by Anahkiasen** [comment]
Latest Compass uses the Can I Use support data, but keep in mind the `-webkit-` prefix might not come from Chrome or Safari but might be added [for a mobile device](http://caniuse.com/#search=box-sizing).

**Comment by chriseppstein** [comment]
This is data-driven in the new release.

**Pull request closed without merging**
