### PR TITLE
user-select mixin with docs and tests

### PR DESCRIPTION
**Pull request by mirisuzanne**
The only problem here is I haven't got the compass docs or tests running on lion yet, so those aren't tested properly. They look right to me. Anyone care to verify and pull?

### CODE REVIEW

**Comment by mirisuzanne** [comment]
all tests pass.

**Comment by chriseppstein** [comment]
@ericam please add a changelog entry and merge it in :)

**Comment by rykov** [comment]
According to [MDN](https://developer.mozilla.org/en/CSS/-moz-user-select), the possible values for _-moz-user-select_ are none, all, text, and -moz-none.  When I do _-moz-user-select: -moz-text_, it is ignored.

The following implementation has worked for me:

```
@mixin user-select($select) {
  $select: unquote($select);
  @include experimental(user-select, $select,
    -moz, -webkit, not -o, not -ms, -khtml, official
  );
}
```

**Comment by mirisuzanne** [comment]
care to submit a patch?

**Comment by rykov** [comment]
Done: chriseppstein/compass#581

**Comment by mirisuzanne** [comment]
merged. thanks!

**Comment by korny** [comment]
I noticed I still have to manually require this mixin in 0.11.7. Shouldn't compass/css3/user-interface be included by compass/css3?

**Pull request merged**
