### PR TITLE
Add 3D transformations with -moz- prefix

### PR DESCRIPTION
**Pull request by ai**
Firefox 10 support 3D transformation, so I add `-moz-` prefix to 3D mixins.

### CODE REVIEW

**Comment by ai** [comment]
Support proof link: https://developer.mozilla.org/en/CSS/transform#Browser_compatibility

**Comment by scottdavis** [comment]
The test case for this needs updated:
https://github.com/chriseppstein/compass/blob/master/test/fixtures/stylesheets/compass/sass/transform.scss
https://github.com/chriseppstein/compass/blob/master/test/fixtures/stylesheets/compass/css/transform.css

**Comment by scottdavis** [comment]
and rebase this against master

**Comment by ai** [comment]
Ouh, I forget about tests O_o. Fixed.

**Comment by scottdavis** [comment]
@paulirish can you weigh in for final approval when it comes to transforms and vendor prefix's im so out of the loop these days

**Comment by paulirish** [comment]
LGTM... but...

 I would suggest enabling the opera and MS prefixes.

Opera will probably end up not shipping with a prefix. But better safe than broken.

IE announced their 3d transform support so http://blogs.msdn.com/b/ie/archive/2012/02/02/css3-3d-transforms-in-ie10.aspx unless you want this stuff to fail in IE10 it should definitely be added.

**Comment by scottdavis** [comment]
Thanks paul @ai if you can get the other prefixes added ill be happy to merge this

**Comment by ai** [comment]
I can add another prefixes in abother pull request ;). IE10 still preversion, so I didn’t check real support. But I need Mozilla support (because 2 major version already support 3D) to promote Compass in conference at Moscow :).

**Comment by scottdavis** [comment]
so you want me to merge this and wait on the others?

**Comment by ai** [comment]
@scottdavis Yes :). I can add just `-ms-` tomorrow in another branch (because it’s another commit by my logic), but I will be without real check. Only by MS docs.

**Comment by scottdavis** [comment]
Im not worried about if it works in IE or not im worried about the other prefixs getting ignored and this feature being incomplete =)

**Comment by ai** [comment]
I will add `-ms-` tomorrow in another branch, because I think that it is another commit. Anyway this commit make Compass better, less incompleted ;).

**Comment by scottdavis** [comment]
Ok ill merge this soon was giving a talk

**Comment by scottdavis** [comment]
ok going to pull this into master rather then stable.

**Comment by scottdavis** [comment]
ive got it merged but looking into test failures then ill push it up

**Comment by scottdavis** [comment]
merged

**Comment by chriseppstein** [comment]
I put it on stable too. non-breaking changes like these are fine to go out in point releases.

**Pull request closed without merging**
