### PR TITLE
sprite: offset-y can take % now

### LINKED ISSUE #1012: Sprite Offset-y doesn't respond to percentage
when you setup a sprite with +spritedir-sprite(icon-large, $offset-x: 100%,  %offset-y:  50%) - the resulting sprite gets a background position of: 100% 50px.

Any number given to $offset-y is converted to px. This is all fine and dandy for vertical sprites, but horizontal ones need to do the 100% to the y offset.

Line 158 in compass / lib / compass / sass_extensions / functions / sprites.rb checks the x offset for percentage and uses it if there is, but nothing is done for the y offset - it just parses out the number and puts the px on there.

Fixes?

### PR DESCRIPTION
**Pull request by JaredSartin**
Fixes #1012

### CODE REVIEW

**Comment by scottdavis** [comment]
can you update the test cases also?

**Comment by scottdavis** [comment]
integration tests for the sass extensions are here: https://github.com/chriseppstein/compass/blob/stable/test/integrations/sprites_test.rb

**Comment by JaredSartin** [comment]
I have not had time to write tests... I will do my best too soon.

**Comment by ken210** [comment]
Would like to see this commit merged

**Comment by scottdavis** [comment]
Awaiting tests before merging

**Comment by norsewulf** [comment]
So this is still a work in progress right?

**Comment by JaredSartin** [comment]
I have had no time to spare to get the test suite running on my machine. It
breaks. If I can get it working, then I will write tests. If anyone else
knows Ruby, feel free to write the tests and make your own fix.

**Comment by developer-collin** [comment]
Would love to see this merged.

**Comment by chriseppstein** [comment]
This has languished long enough. @scottdavis, can you either accept this patch and add some tests or reject it, please?

**Comment by JaredSartin** [comment]
I attempted to run the test suite multiple times and it nearly messed up my
dev environment and still didn't run. Sorry I was not able to provide specs
for this.

**Comment by chriseppstein** [comment]
I've reopened the feature request. I'm closing this PR because there's been too much change since it was initially submitted. Sorry, We're going to do better going forward. Hopefully, someone can resubmit the change against 1.0. Features should be submitted to the master branch, bug fixes to the stable branch.

**Comment by chriseppstein** [comment]
Should be on top of the changes coming in #1771.

**Pull request closed without merging**
