### PR TITLE
Added tint() and shade() color helpers

### PR DESCRIPTION
**Pull request by jhilden**
This closes issue #770

By popular demand added the tint() and shade() Sass color functions.  They allow for a more intuitive way of lightening/darkening a color.
Sass's own lighten() and darken() can be misleading because they only work on the luminance component of a color, while tint() and shade() work by mixing the color with white or black.

Under the hood they are simply using Sass's mix() function, therefore the tests are pretty simple.  Since I assume mix() is well tested.

Added documentation to this page:   http://compass-style.org/reference/compass/helpers/colors/

The functions are based on Bourbon's tint() and shade() functions:  https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/functions/_tint-shade.scss

### CODE REVIEW

**Comment by scottdavis** [comment]
nice work

**Comment by chriseppstein** [comment]
Lovely patch. :heart:

**Comment by jhilden** [comment]
Thanks for merging. Glad you liked it.

Might this make its way into an upcoming 0.12.2 release?

**Comment by chriseppstein** [comment]
yep!

**Pull request merged**
